config/routes.rb
UrlShortener::Application.routes.draw do

  resources :urls

  match '/:short_url' => 'urls#redirect_me'

end

app/models/url.rb
class Url < ActiveRecord::Base

  attr_accessible :long_url, :short_url

  before_create :shorten

  def shorten
    self.short_url = ('a'..'z').to_a.shuffle[0..7].join
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sh_controller.rb
class ShController < ApplicationController

  def index

  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all
  end

  def new
    @new_url = Url.new
  end

  def edit
  end

  def update
  end

  def delete
  end

  def create
    @url = Url.create(params[:url])
    @url.shorten
    redirect_to urls_path
  end

  def show
    @url = Url.find(params[:id])
  end

  def redirect_me
    url_info = Url.find_by_short_url(params[:short_url])
    redirect_to url_info.long_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sh_helper.rb
module ShHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sh/index.html.erb
<h1>Sh#index</h1>
<p>Find me in app/views/sh/index.html.erb</p>

app/views/urls/delete.html.erb
<h1>Urls#delete</h1>
<p>Find me in app/views/urls/delete.html.erb</p>

app/views/urls/edit.html.erb
<h1>Urls#edit</h1>
<p>Find me in app/views/urls/edit.html.erb</p>

app/views/urls/index.html.erb
<h1>Urls#index</h1>
<p>Find me in app/views/urls/index.html.erb</p>

<%= link_to "Create",  new_url_path  %>

<% @urls.each do |url|%>

<h3>  <%= url.long_url %></h3>

<ul>
  <li>
    <%= url.id %>
  <li>
    <%= link_to url.short_url, "localhost:3000/#{url.short_url}" %>
  </ul>
<% end %>

app/views/urls/new.html.erb
<h1>Insert Url in the box below</h1>
<p>

  <%= form_for(@new_url) do |url| %>

    <%= url.label :long_url %>
    <%= url.text_field :long_url %>

    <%= url.submit %>

  <%end%>

app/views/urls/show.html.erb
hi
<%= params[:id] %>
<%= params[:long_url] %>

app/views/urls/update.html.erb
<h1>Urls#update</h1>
<p>Find me in app/views/urls/update.html.erb</p>